version: "3.7"

services:
  registry:
    image: registry:2.7
    networks:
      - front
    volumes:
      - registry_data:/var/lib/registry
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.swiss == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=front

        # http
        - traefik.http.routers.registry.rule=Host(`registry.condensat.space`)
        - traefik.http.routers.registry.entrypoints=web
        - traefik.http.routers.registry.service=registry
        - traefik.http.services.registry.loadBalancer.server.port=5000

        ## registry-low-ratelimit
        - traefik.http.middlewares.registry-low-ratelimit.ratelimit.average=20
        - traefik.http.middlewares.registry-low-ratelimit.ratelimit.burst=2
        - traefik.http.middlewares.registry-low-ratelimit.ratelimit.sourcecriterion.requesthost=true
        - traefik.http.routers.registry.middlewares=registry-low-ratelimit
        ## https-redirect
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true    
        - traefik.http.routers.registry.middlewares=https-redirect

        # tls
        - traefik.http.routers.registry-ssl.tls=true
        - traefik.http.routers.registry-ssl.tls.certResolver=le-ssl
        - traefik.http.routers.registry-ssl.rule=Host(`registry.condensat.space`)
        - traefik.http.routers.registry-ssl.entrypoints=websecure
        - traefik.http.routers.registry-ssl.service=registry
        - traefik.http.services.registry-ssl.loadBalancer.server.port=5000
        ## registry-high-ratelimit
        - traefik.http.middlewares.registry-high-ratelimit.ratelimit.average=1000
        - traefik.http.middlewares.registry-high-ratelimit.ratelimit.burst=100
        - traefik.http.middlewares.registry-high-ratelimit.ratelimit.sourcecriterion.requesthost=true
        - traefik.http.routers.registry-ssl.middlewares=registry-high-ratelimit
        ## retry when scaling
        - traefik.http.middlewares.registry-retry.retry.attempts=4
        - traefik.http.routers.registry-ssl.middlewares=registry-retry
volumes:
  registry_data: {}
      
networks:
  front:
    external: true
