version: "3.7"

services:
  portainer:
    image: registry.condensat.space/portainer:1.23.1
    networks:
      - front
      - portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swiss == true
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=front

        # http
        - traefik.http.routers.portainer.rule=Host(`portainer.condensat.space`)
        - traefik.http.routers.portainer.entrypoints=web
        - traefik.http.routers.portainer.service=portainer
        - traefik.http.services.portainer.loadBalancer.server.port=9000
        ## portainer-low-ratelimit
        - traefik.http.middlewares.portainer-low-ratelimit.ratelimit.average=20
        - traefik.http.middlewares.portainer-low-ratelimit.ratelimit.burst=2
        - traefik.http.middlewares.portainer-low-ratelimit.ratelimit.sourcecriterion.requesthost=true
        - traefik.http.routers.portainer.middlewares=portainer-low-ratelimit

        ## https-redirect
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true    
        - traefik.http.routers.portainer.middlewares=https-redirect

        # tls
        - traefik.http.routers.portainer-ssl.tls=true
        - traefik.http.routers.portainer-ssl.tls.certResolver=le-ssl
        - traefik.http.routers.portainer-ssl.rule=Host(`portainer.condensat.space`)
        - traefik.http.routers.portainer-ssl.entrypoints=websecure
        - traefik.http.routers.portainer-ssl.service=portainer
        - traefik.http.services.portainer-ssl.loadBalancer.server.port=9000
        ## portainer-hight-ratelimit
        - traefik.http.middlewares.portainer-hight-ratelimit.ratelimit.average=1000
        - traefik.http.middlewares.portainer-hight-ratelimit.ratelimit.burst=100
        - traefik.http.middlewares.portainer-hight-ratelimit.ratelimit.sourcecriterion.requesthost=true
        - traefik.http.routers.portainer-ssl.middlewares=portainer-hight-ratelimit

  agent:
    image: registry.condensat.space/portainer_agent:1.5.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    networks:
      - portainer
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  portainer_data: {}
      
networks:
  front:
    external: true
  portainer:
    driver: overlay
    name: portainer
