version: "3.7"

services:
  traefik:
    image: traefik:v2.1
    command:
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - traefik_acme:/etc/traefik/acme
    networks:
      - traefik
      - inbound

volumes:
  traefik_acme: {}

networks:
  traefik:
    driver: overlay
    name: traefik
  inbound:
    driver: overlay
    name: inbound
