version: "3.7"

services:
  nats:
    image: registry.condensat.space/nats:2.1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - condensat

networks:
  condensat:
    driver: overlay
    name: condensat
