version: "3.7"

services:
  cache:
    image: registry.condensat.space/redis:5.0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - private
    volumes:
      - cache_store:/data

  db:
    image: registry.condensat.space/mariadb:10.3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - private
    volumes:
      - db_store:/var/lib/mysql
    secrets:
      - condensat_db_password
    environment:
      MYSQL_USER: condensat
      MYSQL_DATABASE: condensat
      MYSQL_PASSWORD_FILE: /run/secrets/condensat_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/condensat_db_password
    command:
      - --character-set-server=utf8mb4

  dev:
    image: registry.condensat.space/socat:1.0.5
    depends_on:
      - db
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - private
    ports:
      - target: 3306
        published: 3305
        mode: host
    command:
      - tcp-listen:3306,fork,reuseaddr
      - tcp-connect:db:3306

  nats:
    image: registry.condensat.space/nats:2.1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - private
      - condensat

secrets:
  condensat_db_password:
    external: true

volumes:
  cache_store: {}
  db_store: {}

networks:
  private:
    driver: overlay
    name: private 
  condensat:
    driver: overlay
    name: condensat
