version: "3.7"

services:
  code:
    image: registry.condensat.space/gitlab-ce:12.8.2
    networks:
      - front
    volumes:
      - code_config:/etc/gitlab
      - code_data:/var/opt/gitlab
      - code_logs:/var/log/gitlab
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swiss == true
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=front

        # http
        - traefik.http.routers.code.rule=(Host(`code.condensat.tech`)||Host(`code.condensat.space`))
        - traefik.http.routers.code.entrypoints=web
        - traefik.http.routers.code.service=code
        - traefik.http.services.code.loadBalancer.server.port=80
        ## code-low-ratelimit
        - traefik.http.middlewares.code-low-ratelimit.ratelimit.average=20
        - traefik.http.middlewares.code-low-ratelimit.ratelimit.burst=2
        - traefik.http.middlewares.code-low-ratelimit.ratelimit.sourcecriterion.requesthost=true
        - traefik.http.routers.code.middlewares=code-low-ratelimit

        ## https-redirect
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true    
        - traefik.http.routers.code.middlewares=https-redirect

        # tls
        - traefik.http.routers.code-ssl.tls=true
        - traefik.http.routers.code-ssl.tls.certResolver=le-ssl
        - traefik.http.routers.code-ssl.rule=(Host(`code.condensat.tech`)||Host(`code.condensat.space`))
        - traefik.http.routers.code-ssl.entrypoints=websecure
        - traefik.http.routers.code-ssl.service=code
        - traefik.http.services.code-ssl.loadBalancer.server.port=80

        ## code-high-ratelimit
        - traefik.http.middlewares.code-high-ratelimit.ratelimit.average=1000
        - traefik.http.middlewares.code-high-ratelimit.ratelimit.burst=100
        - traefik.http.middlewares.code-high-ratelimit.ratelimit.sourcecriterion.requesthost=true

        ## add middlewares
        - traefik.http.routers.code-ssl.middlewares=code-high-ratelimit

        # Can't filter TCP traffic on SNI, see link below
        # https://community.containo.us/t/routing-ssh-traffic-with-traefik-v2/717/6
        - traefik.tcp.routers.code-ssh.rule=HostSNI(`*`)
        - traefik.tcp.routers.code-ssh.entrypoints=ssh
        - traefik.tcp.routers.code-ssh.service=code-ssh-svc
        - traefik.tcp.services.code-ssh-svc.loadbalancer.server.port=22

volumes:
  code_config: {}
  code_data: {}
  code_logs: {}

networks:
  front:
    external: true
