version: "3.7"

services:
  cache:
    image: registry.condensat.space/redis:5.0
    networks:
      - bank
    volumes:
      - cache_store:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swiss == true
      restart_policy:
        condition: on-failure

  db:
    image: registry.condensat.space/mariadb:10.3
    networks:
      - bank
    volumes:
      - db_store:/var/lib/mysql
    secrets:
      - bank_db_password
    environment:
      MYSQL_USER: condensat
      MYSQL_DATABASE: condensat
      MYSQL_PASSWORD_FILE: /run/secrets/bank_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/bank_db_password
    command:
      - --character-set-server=utf8mb4
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swiss == true
      restart_policy:
        condition: on-failure

  dev:
    image: registry.condensat.space/socat:1.0.5
    depends_on:
      - db
    networks:
      - bank
      - front
    ports:
      - target: 3306
        published: 3306
        mode: host
    command:
      - tcp-listen:3306,fork,reuseaddr
      - tcp-connect:db:3306
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.labels.dev == true
      restart_policy:
        condition: on-failure

secrets:
  bank_db_password:
    external: true

volumes:
  cache_store:
  db_store:
    
networks:
  bank:
    driver: overlay
    name: bank
  front:
    external: true
