version: "3.7"

services:
  cache:
    image: registry.condensat.space/redis:5.0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - bank
    volumes:
      - cache_store:/data

  db:
    image: registry.condensat.space/mariadb:10.3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - bank
    ports:
      # for dev only
      - target: 3306
        published: 3306
        mode: host
    volumes:
      - db_store:/var/lib/mysql
    secrets:
      - bank_db_password
    environment:
      MYSQL_USER: condensat
      MYSQL_DATABASE: condensat
      MYSQL_PASSWORD_FILE: /run/secrets/bank_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/bank_db_password
    command:
      - --character-set-server=utf8mb4

secrets:
  bank_db_password:
    external: true

volumes:
  cache_store:
  db_store:
    
networks:
  bank:
    driver: overlay
    name: bank
