version: "3.7"

services:
  traefik:
    image: traefik:v2.1
    # image: registry.condensat.space/traefik:v2.1
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - traefik_acme:/etc/traefik/acme
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.swiss == true
      restart_policy:
        condition: on-failure

volumes:
  traefik_acme: {}

networks:
  front:
    driver: overlay
    name: front
